name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Cache npm
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_CONVEX_URL: https://convex-shop.sib-utrecht.nl
          VITE_COGNITO_USER_POOL_ID: eu-central-1_Ecd3uxa0G
          VITE_COGNITO_CLIENT_ID: 3saoma3t11p04k0j3se6jvenab
          
        run: npm run build --if-present

      - name: Add CNAME for custom domain
        run: echo 'shop.sib-utrecht.nl' > ./dist/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
